file_format: "1"
id: anise60b
name: Anise60B Rev. 1
type: shield
url: https://github.com/ngzh/anise60b
requires: [anise_ctl]
features:
  - keys
  - underglow
siblings:
  - anise60b_left
  - anise60b_right
