file_format: "1"
id: quefrency
name: Quefrency Rev. 1
type: shield
url: https://github.com/keebio/quefrency-rev1-pcb
requires: [pro_micro]
features:
  - keys
  - underglow
siblings:
  - quefrency_left
  - quefrency_right
